server:
  port: 8101
spring:
  application:
    name: transaction-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/transaction_db
    username: user
    password: "10001"
  flyway:
    url: jdbc:postgresql://localhost:5433/transaction_db
    user: user
    password: "10001"
    locations: classpath:db/migration
web:
  client:
    account: http://account-service:8100/v