server:
  port: 8101
spring:
  application:
    name: transaction-service
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USERNAME}
    password: ${SPRING_FLYWAY_PASSWORD}
    locations: ${SPRING_FLYWAY_LOCATIONS}
web:
  client:
    account: ${ACCOUNT_SERVICE_URL}