server:
  port: 8100
spring:
  application:
    name: account-service
  r2dbc:
    url: r2dbc:mysql://localhost:3307/account_db
    username: user
    password: "root123"
  flyway:
    url: jdbc:mysql://localhost:3307/account_db
    user: user
    password: "root123"
    locations: classpath:db/migration